###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:
    webserver:
      image: nginx:alpine
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8040:80"

    mariadb:
      image: mariadb:10.1
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=simplon
        - MYSQL_USER=simplon
        - MYSQL_PASSWORD=simplon
      ports:
        - "3307:3306"

    php-fpm:
      build: phpdocker/php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini


    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - mariadb:mariadb
        ports:
            - 8000:80
        environment:
            MYSQL_USER: simplon
            MYSQL_PASSWORD: simplon
            MYSQL_ROOT_PASSWORD: root 